### ISSUE TITLE
SyntaxError upon import

### ISSUE THREAD

**Issue by xbra** [sendinblue/APIv3-python-library#45]
`import sib_api_v3_sdk` fails with the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/sib_api_v3_sdk/__init__.py", line 19, in <module>
    from sib_api_v3_sdk.api.account_api import AccountApi
  File "/usr/lib/python3.8/site-packages/sib_api_v3_sdk/api/__init__.py", line 6, in <module>
    from sib_api_v3_sdk.api.account_api import AccountApi
  File "/usr/lib/python3.8/site-packages/sib_api_v3_sdk/api/account_api.py", line 119
    async=params.get('async'),
    ^
SyntaxError: invalid syntax
```

**Tested versions:** latest git and 4.2.2
```
$ python --version
Python 3.8.0
```

**Steps to reproduce:**
1. `sudo pip install git+https://github.com/sendinblue/APIv3-python-library.git`
2. `$ python -c "import sib_api_v3_sdk"`

Any help is highly appreciated.

**Comment by koloyyee** [comment]
same error

**Comment by edmondodriscoll** [comment]
Same for me

**Comment by AmiraAyadi** [comment]
same for me too

**Comment by aakanksha-sib** [comment]
Hi @xbra , @koloyyee , @edmondodriscoll , @AmiraAyadi 
The python library is now compatible with v3.7
Please use latest version.

Thanks!
Sendinblue team
