### ISSUE TITLE
Switch to api.brevo.com?

### ISSUE THREAD

**Issue by tarraschk** [sendinblue/APIv3-python-library#90]
Hello,

we use the SendInBlue API to send some messages.

We mostly rely on the `sib_api_v3_sdk.SendSmtpEmail`

We just received the email regarding the migration from `smtp-relay.sendinblue.com` to `smtp-relay.brevo.com`.

Is there anything to change as well regarding the API?

The current host is  `https://api.sendinblue.com/v3` if we look here:

https://github.com/sendinblue/APIv3-python-library/blob/master/sib_api_v3_sdk/configuration.py#L43

I suppose that we will have to use `https://api.brevo.com/v3/` at some point.

1. Do you plan to keep api.sendinblue.com as well?
2. Should we change to api.brevo.com? If so, within how many days?
3. Should we also change something to the code, or the `sib_api_v3_sdk.SendSmtpEmail` function will still work well as long as we use api.brevo.com instead of api.sendinblue.com?

Best regards

**Comment by mathieuruellanmyscript** [comment]
Issue today :

```
2024-04-16 15:28:46,532 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f439f5e1970>: Failed to resolve 'api.sendinblue.com' ([Errno -3] Temporary failure in name resolution)")': /v3/contacts/folders?limit=10&offset=0
^C^CTraceback (most recent call last):
  File "/mnt/.local/lib/python3.12/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/.local/lib/python3.12/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 963, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

```

**Comment by mathieuruellanmyscript** [comment]
At least, add a configuration parameter to override the api endpoint ...

**Comment by bfontaine** [comment]
@mathieuruellanmyscript unless I’m missing something, it’s already possible:
```python
configuration = sib_api_v3_sdk.Configuration()
configuration.host = "https://api.brevo.com/v3"
api_instance = sib_api_v3_sdk.AccountApi(sib_api_v3_sdk.ApiClient(configuration))
```
